### ISSUE TITLE
Some windows problems

### ISSUE THREAD

**Issue by mirh** [RippeR37/GL_vs_VK#5]
First, afaiu you are missing `../../../third_party/vulkan/src/;../../../third_party/vulkan-hpp/;` from include directories. 
Second, I think you should be specifying in the readme Vulkan SDK needs to be installed (for vulkan-1.lib)
Third, something requires glfw3.lib, which means you are gonna need GLFW [bins](http://www.glfw.org/download.html) too. 

And last but not least, for as much on the one hand I believe I improved the thing with #4.. I'm not really sure storing binaries in source control is really the best solution. 
Couldn't you just point to sources, then having compile them?
Or perhaps modify the install_msvc_dependencies script to just download end binaries.

**Comment by RippeR37** [comment]
>First, afaiu you are missing ../../../third_party/vulkan/src/;../../../third_party/vulkan-hpp/; from include directories.

Yep, I forgot to add this to MSVC project too. I'll fix it with some other changes soon.

>Second, I think you should be specifying in the readme Vulkan SDK needs to be installed (for vulkan-1.lib)

There already is something like: `VulkanSDK might be needed on Windows (v1.0.46.0 or higher)`. Actually one doesn't have to use SDK if he want to manually override paths to libraries (e.g. using CMake on Windows) and will provide path to Vulkan's loader himself, so it's not hard-requirement as you only need headers (already added as submodules and lib file). 

>Third, something requires glfw3.lib, which means you are gonna need GLFW bins too.

Again, please read `README.md`, it states that you use script `install_msvc_dependencies.bat` which should build GLFW3 on your computer - no need to provide binaries there.

>I'm not really sure storing binaries in source control is really the best solution.
Couldn't you just point to sources, then having compile them?
Or perhaps modify the install_msvc_dependencies script to just download end binaries.

Building GLEW on Windows just from GIT repository is not that easy as it requires some extra tools to download first data regarding OpenGL specification and then parsing it. Unfortunately repository owner doesn't include this generated `glew.c` file in it, so to make things easier I added GLEW binaries for windows in source. Also note, that putting small binaries which won't change is not that problematic. It would be a bigger problem if these would change frequently.

So only the first mentioned problem will be handled here.

**Comment by mirh** [comment]
Mhh.. I guess that may something to do with msbuild not being in path. 

```
for /f "skip=2 tokens=2,*" %%A in ('reg.exe query "HKLM\SOFTWARE\Microsoft\MSBuild\ToolsVersions\14.0" /v MSBuildToolsPath /reg:32 2^> nul') do SET "MSBUILDDIR=%%B"
for /f "skip=2 tokens=2,*" %%A in ('reg.exe query "HKLM\SOFTWARE\Microsoft\VisualStudio\SxS\VS7" /v 15.0 /reg:32 2^> nul') do SET "MSBUILDDIR=%%BMSBuild\15.0\Bin\"

SET PATH=%PATH%;%MSBUILDDIR%

MSBuild.exe ALL_BUILD.vcxproj >nul 2>&1
MSBuild.exe ALL_BUILD.vcxproj /property:Configuration=Release >nul 2>&1
IF ERRORLEVEL 9009 IF NOT EXIST "%MSBUILDDIR%" (echo "Couldn't find MSBuild path") & pause
```

This elegantly solves the situation imo. 
Otherwise you'd have to rely on [external](https://github.com/Microsoft/vswhere/wiki/Find-MSBuild) [tools](https://github.com/deadlydog/Invoke-MsBuild).

**Comment by RippeR37** [comment]
I've fixed paths to Vulkan/Vulkan-Hpp headers. Linker still searched by default for loader in Vulkan_SDK folder, but as this is de-factor standard on Windows at this moment, I'm not going to support other possibilities by default. You can always use CMake and add paths on your own.

As for above solution - again, this project doesn't aim to give best-user-experience and is intended at most for "power-users" only. Having MSBuild in `PATH` (which I believe is added there by default) is on user who wants to use MSVC project. I'm not a fan of using such *hacks* to work around users problems.

**Comment by mirh** [comment]
MSBuild isn't added by default. 
Otherwise I mean yes, I would have agreed.

**Comment by RippeR37** [comment]
@mirh I've created separate issue for that. You're right, it's not added there by default - my mistake. I must have added it so long ago that I simply forgot about it.

Anyway, I'll deal with this when I have some more time to tinker with it, as it's not a priority for me right now. Anyway - thanks for reporting it.

**Comment by mirh** [comment]
Cool. 
Even though users haven't [7za](https://github.com/RippeR37/GL_vs_VK/pull/4) in path either 🙃
