### ISSUE TITLE
Vulkan is initialized even for GL tests

### ISSUE THREAD

**Issue by mirh** [RippeR37/GL_vs_VK#6]
I guess it's kind of dumb given the actual scope of the project, but if I wanted to use this to make comparisons "inside" the same api, it fails on gpus with no vulkan dll

**Comment by RippeR37** [comment]
As suggested, this is mainly to compare both APIs so it' doesn't make sense that user should select which APIs will be enabled (if there are only two of them). So for now, such functionality will not be implemented anytime soon.

Maybe in the future there will be a CMake switch to disable Vulkan side, but for now there are no such plans.

**Comment by mirh** [comment]
Tbh I was just imaging the program to load vulkan when vulkan is requested.

**Comment by RippeR37** [comment]
Again - this is a project for my master's thesis and it's strictly meant to compare these two APIs, so no point in having only one of these. Also loading library dynamically just before launching given test is messy and AFAIK system-dependent so I'm not even considering going this way.

Other solution would be to build different executables for each API and this would be much cleaner, but again - not in scope of this project.

PS. Note that you don't need Vulkan-supporting GPUs or even drivers, you only need Vulkan loader for it to work. So it's not like somebody really can't use this.

**Comment by mirh** [comment]
Nice to know all, thank you.

**Comment by mirh** [comment]
Just tested. 
You don't know how much valuable your testcases are, even between the same api. Really thank you.
