### ISSUE TITLE
Vulkan Multithreading

### ISSUE THREAD

**Issue by MNannig** [RippeR37/GL_vs_VK#8]
Hey Damian sorry to write you here but i didn't find any other way to do it more privately.
Do you have anything on Vulkan multithreading? like a basics code or hello world except from the example from Sascha Willems. I'm trying to do something similar to your benchmark but right now i only have it on single core.

**Comment by mirh** [comment]
[[1](https://www.reddit.com/r/vulkan/comments/52aodq/multithreading_in_vulkan_where_should_i_start/)] [[2](https://www.imgtec.com/blog/vulkan-scaling-to-multiple-threads/)] ?

**Comment by RippeR37** [comment]
@MNannig Hey, I'm sorry but I don't have any extensive resources about programming multithreaded renderers with Vulkan. My work here is based on Vulkan specification, `Vulkan Programming Guide` book and a lot of knowledge collected from many posts or small articles throughout the web (e.g. Reddit where some users explained in-depth how to do it right). Also - a lot of "try, verify, benchmark and try again...". I haven't found any in-depth all-in-one articles on that subject.

Feel free also to make diffs between my single-threaded tests and their multithreaded versions. They were usually built as:
- create single-threaded version,
- copy and extend it to use multiple threads (usually by adding some code and changing logic in few places to dispatch work to multiple threads).

It should be easy to spot what changed and why
